services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: knowmap_api
    ports:
      - "5010:5010"
    restart: always
    networks:
      - knowmap_network
    volumes:
      - ./feedback.csv:/app/feedback.csv

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: knowmap_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:5010
    depends_on:
      - backend
    restart: always
    networks:
      - knowmap_network
    volumes:
      - ./feedback.csv:/app/feedback.csv
      
networks:
  knowmap_network:
    driver: bridge
